replicaCount: 2

appInClusterNamespace: cumulusbank

targetCluster:
  labelSelector:
    matchLabels:
      name: thinkgke2
      
targetClusteraisvc:
  labelSelector:
    matchLabels:
      name: thinkgke2
chartRepoURL: https://raw.githubusercontent.com/ibm-cloud-architecture/kubernetes-multicloud-management/v312/demos/guestbook/chart-packages
