apiVersion: mcm.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: {{ template "cumulusbank.fullname" . }}-odmsvc
  labels:
    app: {{ template "cumulusbank.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    name: {{ template "cumulusbank.fullname" . }}-odmsvc
    servicekind: CacheService
spec:
  deployer:
    kind: helm
    helm:
      chartURL: "https://raw.githubusercontent.com/cumulus-bank/ODM-Microservice/master/chart/odmsvc-0.1.0.tgz"
      namespace: {{ .Values.appInClusterNamespace }}