apiVersion: mcm.ibm.com/v1alpha1
kind: PlacementBinding
metadata:
  name: {{ template "cumulusbank.fullname" . }}
  labels:
    app: {{ template "cumulusbank.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    name: {{ template "cumulusbank.fullname" . }}
    servicekind: CacheService
placementRef:
  apiGroup: mcm.ibm.com
  kind: PlacementPolicy
  name: {{ template "cumulusbank.fullname" . }}
subjects:
- apiGroup: mcm.ibm.com
  kind: Deployable
  name: {{ template "cumulusbank.fullname" . }}-accountsvc
- apiGroup: mcm.ibm.com
  kind: Deployable
  name: {{ template "cumulusbank.fullname" . }}-mongodbsvc
- apiGroup: mcm.ibm.com
  kind: Deployable
  name: {{ template "cumulusbank.fullname" . }}-maria
- apiGroup: mcm.ibm.com
  kind: Deployable
  name: {{ template "cumulusbank.fullname" . }}-authsvc
- apiGroup: mcm.ibm.com
  kind: Deployable
  name: {{ template "cumulusbank.fullname" . }}-odm
- apiGroup: mcm.ibm.com
  kind: Deployable
  name: {{ template "cumulusbank.fullname" . }}-odmsvc
# - apiGroup: mcm.ibm.com
#   kind: Deployable
#   name: {{ template "cumulusbank.fullname" . }}-aisvc